---
- hosts: localhost
  become: yes
  become_method: sudo
  become_user: root
  roles:
    - { role: ansible-role-speckleserver }
    - { role: geerlingguy.nginx }
  vars:
    speckleserver_server_name: 'SpeckleServer Development Environment'
    speckleserver_url: 'http://speckle.example.com'
    speckleserver_mongodb_uri: 'mongodb://mongo.example.com:27017/speckle'
    speckleserver_redis_host: 'redis.example.com'
    speckleserver_version: "1.5.2"
    speckleadmin_version: "0.2.11"
    speckleserver_listen_ip: "127.0.0.1"
    speckleserver_port: 3000

    nginx_vhosts:
      - listen: "443 ssl http2"
        state: "present"
        server_name: "your.fqdn your.host.name"
        root: "/home/speckle/speckleserver/"
        index: "index.html index.htm"
        access_log: "/var/log/nginx/speckleserver-access.log"
        error_log: "/var/log/nginx/speckleserver-error.log"
        template: "{{ nginx_vhost_template }}"
        filename: "speckleserver.conf"
        extra_parameters: |
           map $http_upgrade $connection_upgrade {
                default upgrade;
                '' close;
           }

           upstream speckleserver {
                       server {{speckleserver_listen_ip }}:{{ speckleserver_port }};
           }
           location / {
              proxy_set_header Upgrade $http_upgrade;
              proxy_set_header Connection $connection_upgrade;
              proxy_http_version 1.1;
              proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
              proxy_set_header Host $host;
              proxy_pass http://speckleserver;
              proxy_read_timeout 86400;
           }

           ssl_certificate     /etc/pki/tls/certs/localhost.pema;
           ssl_certificate_key /etc/pki/tls/private/localhost.key;
           ssl_protocols       TLSv1.1 TLSv1.2;
           ssl_ciphers         HIGH:!aNULL:!MD5;

      - listen: "80"
        server_name: "your.fqdn your.host.name"
        return: "301  https://$host$request_uri"
        filename: "speckle-http.conf"
