---
- name: "Ensure packaging dependencies are installed (Debian)"
  apt:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - gpg-agent
      - apt-transport-https
      - aptitude
      - python-apt

- name: "Import NodeJS APT/DEB signing key"
  apt_key:
    url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
    state: present

- name: "Install NodeJS 10.x repository info from NodeSource (Debian)"
  apt_repository:
    repo: |
      deb https://deb.nodesource.com/node_10.x {{ ansible_distribution_release }} main
    state: present
    update_cache: yes

- name: "Install nodejs 10.x package"
  apt:
    name: nodejs
    state: present
