---
- name: "Install NodeJS 10.x repository release package from NodeSource"
  yum:
    name: https://rpm.nodesource.com/pub_10.x/el/7/x86_64/nodesource-release-el7-1.noarch.rpm
    state: installed

- name: "Install nodejs 10.x package"
  yum:
    name: nodejs
    state: installed

- name: "Enaure a local speckle group exists"
  group:
    name: speckle
    state: present

- name: "Ensure that a local speckle user exists with appropriate settings"
  user:
    name: speckle
    state: present
    group: speckle
    create_home: true
    home: /home/speckle/
    comment: "Speckleserver service user"
    shell: "/bin/bash"

- name: "Ensure that the speckleserver subdirectory exists"
  file:
    path: /home/speckle/speckleserver
    state: directory
    owner: speckle
    group: speckle
    mode: 0755

- name: "Get release info for Speckleserver from github"
  uri:
    url: https://api.github.com/repos/speckleworks/SpeckleServer/releases/tags/v{{ speckleserver_version }}
    return_content: true
  register: speckleserver_github
  when: speckleserver_version != "latest"

- name: "Get release info for Speckleserver from github (latest)"
  uri:
    url: "https://api.github.com/repos/speckleworks/SpeckleServer/releases/latest"
    return_content: true
  register: speckleserver_github
  when: speckleserver_version == "latest"

- name: "Version of Speckleserver we are requesting"
  debug:
    var: speckleserver_version

- name: "Tarball URL from Github for the SpeckleServer archiv we want"
  debug:
    var: speckleserver_github.json.tarball_url

- name: "Install the SpeckleServer application codebase"
  unarchive:
    src: "{{ speckleserver_github.json.tarball_url }}"
    dest: /home/speckle/speckleserver/
    owner: speckle
    group: speckle
    remote_src: yes
    extra_opts: [ --strip-components=1 ]

- name: "Install the SpeckleAdmin plugin to the plugins subdirectory"
  unarchive:
    src: "https://codeload.github.com/speckleworks/SpeckleAdmin/tar.gz/v{{ speckleadmin_version }}"
    dest: "/home/speckle/speckleserver/plugins/"
    remote_src: yes

- name: "Install the application's required libraries via npm"
  npm:
    path: /home/speckle/speckleserver/

- name: "Configure the speckleserver instance via .env file"
  template:
    src: templates/speckleserver-env.j2
    dest: /home/speckle/speckleserver/.env
    owner: speckle
    group: speckle
    mode: 0644

- name: "Create a systemd unit service file for Speckleserver"
  copy:
    src: files/speckleserver.service
    dest: /usr/lib/systemd/system/speckleserver.service
    owner: root
    group: root
    mode: 0750

- name: "Enable and start the Speckleserver service"
  service:
    name: speckleserver
    enabled: true
    state: started
