---
- name: "Install NodeJS official repositories and packages"
  include_tasks: "{{ item }}"
  with_first_found:
    - install-{{ ansible_distribution }}.yml
    - install-{{ ansible_os_family }}.yml

- name: "Enaure a local speckle group exists"
  group:
    name: speckle
    state: present

- name: "Ensure that a local speckle user exists with appropriate settings"
  user:
    name: speckle
    state: present
    group: speckle
    create_home: true
    home: /home/speckle/
    comment: "Speckleserver service user"
    shell: "/bin/bash"

- name: "MIGRATE: Check we have an unversioned speckle app dir"
  stat:
    path: /home/speckle/speckleserver/
  register: legacy_specklepath
  tags:
    - migrate

- name: "MIGRATE: Move unversioned speckle app dir to a versioned one"
  command: "mv /home/speckle/speckleserver/ /home/speckle/speckleserver-{{ speckleserver_version }}"
  args:
    creates: "/home/speckle/speckleserver-{{ speckleserver_version }}"
    removes: /home/speckle/speckleserver
  when: legacy_specklepath.stat.islnk is defined and legacy_specklepath.stat.islnk == False
  tags:
    - migrate

- name: "Ensure that the speckleserver subdirectory exists"
  file:
    path: "/home/speckle/speckleserver-{{ speckleserver_version }}"
    state: directory
    owner: speckle
    group: speckle
    mode: 0755

- name: "Symlink base application root dir to versioned app directory"
  file:
    path: /home/speckle/speckleserver
    src: "/home/speckle/speckleserver-{{ speckleserver_version }}/"
    owner: speckle
    group: speckle
    state: link

- name: "Release info: Where to find release info (set version)"
  set_fact:
    speckleserver_api_stem: "tags/v{{ speckleserver_version }}"

- name: "Release info: Where to find release info (latest)"
  set_fact:
    speckleserver_api_stem: "latest"
  when: speckleserver_version == "latest"

- name: "INFO: Version of Speckleserver we are requesting"
  debug:
    msg: "We are planning to install the {{speckleserver_version }} release of SpeckleServer"

- name: "Get release info for Speckleserver from github"
  uri:
    url: |
      https://api.github.com/repos/speckleworks/SpeckleServer/releases/{{ speckleserver_api_stem }}
    return_content: true
  register: speckleserver_github
  until: speckleserver_github.json.tarball_url is defined
  retries: 5
  delay: 10

- name: "INFO: Semantic release version info for the latest release"
  debug:
    msg: "FYI: The latest release points to version {{ speckleserver_github.json.tag_name }}"
  when: speckleserver_version == "latest"

- name: "Install the SpeckleServer application codebase"
  unarchive:
    src: "{{ speckleserver_github.json.tarball_url }}"
    dest: "/home/speckle/speckleserver-{{ speckleserver_version }}"
    owner: speckle
    group: speckle
    remote_src: yes
    extra_opts: [ --strip-components=1 ]
    creates: "/home/speckle/speckleserver-{{ speckleserver_version }}/.env-base"
  register: unpacked_base
  until: unpacked_base is succeeded
  retries: 5
  delay: 10

- name: "Install the SpeckleAdmin plugin to the plugins subdirectory"
  unarchive:
    src: |
      https://codeload.github.com/speckleworks/SpeckleAdmin/tar.gz/v{{ speckleadmin_version }}
    dest: "/home/speckle/speckleserver-{{speckleserver_version}}/plugins/"
    owner: speckle
    group: speckle
    remote_src: yes
  register: unpacked_plugin
  until: unpacked_plugin is succeeded
  retries: 5
  delay: 10

- name: "Install the application's required libraries via npm"
  npm:
    path: /home/speckle/speckleserver/

- name: "Configure the speckleserver instance via .env file"
  template:
    src: templates/speckleserver-env.j2
    dest: /home/speckle/speckleserver/.env
    owner: speckle
    group: speckle
    mode: 0644
  notify:
    - "Restart SpeckleServer"

- name: "Create a systemd unit service file for Speckleserver"
  copy:
    src: files/speckleserver.service
    dest: /usr/lib/systemd/system/speckleserver.service
    owner: root
    group: root
    mode: 0750

- name: "Enable and start the Speckleserver service"
  service:
    name: speckleserver
    enabled: true
    state: started
