---
# tasks file for ansible-role-speckleadmin
#
- name: "Check if SpeckleServer is installed correctly"
  stat:
    path: "/home/speckle/speckleserver-{{ speckleserver_version }}/plugins/"
    follow: yes
  register: plugindir

- name: "Get release info for Speckleserver from github"
  uri:
    url: |
      https://api.github.com/repos/speckleworks/SpeckleServer/releases/{{ speckleserver_api_stem }}
    return_content: true
  register: speckleadmin_ghub
  until: speckleadmin_ghub.json.tarball_url is defined
  retries: 5
  delay: 10

- name: "INFO: Semantic release version info for the latest release of SpeckleAdmin"
  debug:
    msg: "FYI: The latest release points to version {{ speckleadmin_ghub.json.tag_name }}"
  when: speckleadmin_version == "latest"

- name: "Ensure that the speckleAdmin plugin subdirectory exists"
  file:
    path: "/home/speckle/speckleserver-{{ speckleserver_version }}/SpeckleAdmin/"
    state: directory
    owner: speckle
    group: speckle
    mode: 0755
  when:
    - plugindir.stat.isdir

- name: "Install the SpeckleAdmin plugin codebase"
  unarchive:
    src: "{{ speckleadmin_ghub.json.tarball_url }}"
    dest: "/home/speckle/speckleserver-{{ speckleserver_version }}/plugins/SpeckleAdmin/"
    owner: speckle
    group: speckle
    remote_src: yes
    extra_opts: [ --strip-components=1 ]
    creates: "/home/speckle/speckleserver-{{ speckleserver_version }}/plugins/SpeckleAdmin/speckle-plugin-manifest.json"
  register: unpacked_admin
  until: unpacked_admin is succeeded
  retries: 5
  delay: 10
  when:
    - plugindir.stat.isdir

- name: "Install the nodejs modules required for the plugin"
  npm:
    path: "/home/speckle/speckleserver-{{ speckleserver_version }}/plugins/SpeckleAdmin/"
    state: present
  become: yes
  become_user: speckle
  when:
    - plugindir.stat.isdir

- name: "Run the production optimisation process for SpeckleAdmin"
  command: npm run build
  args:
    chdir: "/home/speckle/speckleserver-{{ speckleserver_version }}/plugins/SpeckleAdmin/"
  become: yes
  become_user: speckle
  when:
    - plugindir.stat.isdir
  notify:
    - "Restart SpeckleServer"
