---
# tasks file for ansible-role-speckleadmin
#
- name: "Check if SpeckleServer is installed correctly"
  stat:
    path: "/home/speckle/speckleserver/plugins/"
    follow: yes
  register: plugindir

- name: "Install git command line tool"
  package:
    name: "git"
    state: present
  when:
    - plugindir.stat.isdir

- name: "Pull SpeckleAdmin from Github"
  git:
    repo: "https://github.com/speckleworks/SpeckleAdmin.git"
    dest: "/home/speckle/speckleserver/plugins/SpeckleAdmin/"
    force: true
  become: yes
  become_user: speckle
  when:
    - plugindir.stat.isdir

- name: "Install the nodejs modules required for the plugin"
  npm:
    path: "/home/speckle/speckleserver/plugins/SpeckleAdmin/"
    state: present
  become: yes
  become_user: speckle
  when:
    - plugindir.stat.isdir

- name: "Run the production optimisation process for SpeckleAdmin"
  command: npm run build
  args:
    chdir: "/home/speckle/speckleserver/plugins/SpeckleAdmin/"
  become: yes
  become_user: speckle
  when:
    - plugindir.stat.isdir
  notify:
    - "Restart SpeckleServer"
