---
- name: Converge
  hosts: all
  roles:
    - role: ansible-role-speckleserver
    - role: geerlingguy.redis
    - role: undergreen.mongodb
  vars:
    speckleserver_version: "latest"
    speckleserver_admin: true
    speckleserver_send_email: true
    speckleserver_first_user_admin: true
    speckle_email_config:
      - smtp_host: "localhost"
      - smtp_port: 25
      - smtp_email_from: "nobody@arup.com"
